server:
  port: 8761 
  
spring:
   profiles: dev
   application:
     name: springcloud-config-eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
---
server:
  port: 8762
  
spring:
   profiles: test
   application:
     name: springcloud-config-eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/