server:
  port: 8100
spring:
   profiles: dev
   application:
     name: emp-consumer
eureka:
   client:
      service-url:
         defaultZone: http://127.0.0.1:8761/eureka/
---
server:
  port: 8101
spring:
   profiles: test
   application:
     name: emp-consumer    
eureka:
   client:
      service-url:
         defaultZone: http://127.0.0.1:8761/eureka/  