server:
  port: 8001
spring:
   profiles: dev
   application:
     name: emp-provider
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/springdata
       username: root
       password: 123456
       type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.sxt.pojo
logging:
  level: 
    com.sxt.mapper: debug 
eureka:
   client:
      service-url:
         defaultZone: http://127.0.0.1:8761/eureka/
---
server:
  port: 8002
spring:
   profiles: test
   application:
     name: emp-provider
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/springdata
       username: root
       password: 123456
       type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.sxt.pojo
logging:
  level: 
    com.sxt.mapper: debug      
eureka:
   client:
      service-url:
         defaultZone: http://127.0.0.1:8761/eureka/  
